### ISSUE TITLE
Project Tracking

### ISSUE THREAD

**Issue by mjbernet3** [GTBitsOfGood/national-npp#34]
## What/Why?

Nonprofits and chapters should be able to monitor and progress projects together.

## Tasks

-  [ ] Nonprofits can view all of their projects
-  [ ] Nonprofits can create a new project
-  [ ] Nonprofits can check the status of a project
-  [ ] Nonprofits can see the chapter contact of a project
-  [ ] Nonprofits can cancel a project
-  [ ] Chapters can view unassigned projects
-  [ ] Chapters can assign projects to themselves
-  [ ] Chapters can view all of their projects
-  [ ] Chapters can check the status of a project
-  [ ] Chapters can assign an "in-progress" contact to a project
-  [ ] Chapters can see the nonprofit contact of a project
-  [ ] Chapters can cancel or reject a project
