### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mjbernet3** [GTBitsOfGood/national-npp#39]
## What/Why?

Users should be able to sign up and sign in to the application.

## Tasks

-  [ ] Users can create a new account
-  [ ] Users can create a new nonprofit following account creation
-  [ ] Users can sign in to the application
-  [ ] Users can sign out of the application
