### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by mjbernet3** [GTBitsOfGood/national-npp#40]
## What/Why?

Users should be notified when important events happen within the application.

## Tasks

-  [ ] Notify nonprofits when chapters update the status of a project
-  [ ] Notify chapters when nonprofits update the status of a project
-  [ ] Notify chapters when a new project is added
-  [ ] Notify chapters when a new issue is reported
-  [ ] Notify nonprofits when an issue is resolved or closed
